import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import pdfParse from 'pdf-parse';
import { Document, Packer, Paragraph, TextRun } from 'docx';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Helper to run shell commands as promises
const execPromise = (cmd) => {
  return new Promise((resolve, reject) => {
    exec(cmd, (error, stdout, stderr) => {
      if (error) {
        reject(error);
      } else {
        resolve({ stdout, stderr });
      }
    });
  });
};

export const wordToPdf = async (inputWordPath) => {
  const isWindows = process.platform === 'win32';
  const uniqueId = Date.now() + '-' + Math.round(Math.random() * 1e9);
  const uploadsDir = path.resolve(path.join(__dirname, '../../uploads'));
  const absoluteInputPath = path.resolve(inputWordPath);

  if (isWindows) {
    const tempPdfPath = path.join(uploadsDir, `temp_${uniqueId}.pdf`);
    const psScriptPath = path.join(uploadsDir, `convert_${uniqueId}.ps1`);
    const absoluteOutputPath = path.resolve(tempPdfPath);

    const psScriptContent = `
$ErrorActionPreference = 'Stop'
try {
    $word = New-Object -ComObject Word.Application
    $word.Visible = $false
    $doc = $word.Documents.Open("${absoluteInputPath.replace(/\\/g, '\\\\')}")
    # 17 represents wdFormatPDF
    $doc.SaveAs("${absoluteOutputPath.replace(/\\/g, '\\\\')}", 17)
    $doc.Close()
    $word.Quit()
    Write-Host "Success"
} catch {
    Write-Error $_.Exception.Message
    if ($word) { $word.Quit() }
    exit 1
}
`;
    try {
      fs.writeFileSync(psScriptPath, psScriptContent, 'utf-8');
      const cmd = `powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "${psScriptPath}"`;
      await execPromise(cmd);

      if (!fs.existsSync(tempPdfPath)) {
        throw new Error('PDF file was not generated by PowerShell script');
      }

      const pdfBytes = fs.readFileSync(tempPdfPath);
      return pdfBytes;
    } catch (err) {
      console.error('Word to PDF conversion error (PowerShell):', err);
      throw new Error(`Word to PDF conversion failed: ${err.message}`);
    } finally {
      if (fs.existsSync(psScriptPath)) {
        try { fs.unlinkSync(psScriptPath); } catch (_) {}
      }
      if (fs.existsSync(tempPdfPath)) {
        try { fs.unlinkSync(tempPdfPath); } catch (_) {}
      }
    }
  } else {
    // Linux/Docker - Use LibreOffice/soffice
    const tempInputName = `temp_${uniqueId}.docx`;
    const tempInputPath = path.join(uploadsDir, tempInputName);
    const tempPdfName = `temp_${uniqueId}.pdf`;
    const tempPdfPath = path.join(uploadsDir, tempPdfName);

    try {
      // Copy the input file to the temp path so LibreOffice names the output correctly
      fs.copyFileSync(absoluteInputPath, tempInputPath);

      // Execute soffice command
      const cmd = `soffice --headless --convert-to pdf --outdir "${uploadsDir}" "${tempInputPath}"`;
      await execPromise(cmd);

      if (!fs.existsSync(tempPdfPath)) {
        throw new Error('PDF file was not generated by LibreOffice');
      }

      const pdfBytes = fs.readFileSync(tempPdfPath);
      return pdfBytes;
    } catch (err) {
      console.error('Word to PDF conversion error (LibreOffice):', err);
      throw new Error(`Word to PDF conversion failed: ${err.message}`);
    } finally {
      if (fs.existsSync(tempInputPath)) {
        try { fs.unlinkSync(tempInputPath); } catch (_) {}
      }
      if (fs.existsSync(tempPdfPath)) {
        try { fs.unlinkSync(tempPdfPath); } catch (_) {}
      }
    }
  }
};

/**
 * Converts a PDF to a Word Document by extracting text and packaging it.
 */
export const pdfToWord = async (pdfPath) => {
  const pdfBytes = fs.readFileSync(pdfPath);
  
  // Extract text
  const parseResult = await pdfParse(pdfBytes);
  const text = parseResult.text || '';

  // Split text by newlines and filter/clean empty lines
  const lines = text.split(/\r?\n/);
  
  const paragraphs = lines.map(line => {
    return new Paragraph({
      children: [
        new TextRun({
          text: line,
          font: 'Calibri',
          size: 24 // 12pt
        })
      ],
      spacing: {
        after: 120 // 6pt spacing after paragraphs
      }
    });
  });

  // Create docx document
  const doc = new Document({
    sections: [{
      properties: {},
      children: paragraphs
    }]
  });

  const docxBuffer = await Packer.toBuffer(doc);
  return docxBuffer;
};
